-- MySQL Script generated by MySQL Workbench
-- Tue Jun 17 16:45:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` INT NOT NULL,
  `foto_perfil` VARCHAR(45) NOT NULL,
  `Data_criacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`, `nome`, `email`, `senha`, `foto_perfil`, `Data_criacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `likes_gerais` INT NOT NULL,
  `desliks_gerais` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `nome`, `logo`, `likes_gerais`, `desliks_gerais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentarios` (
  `idComentarios` INT NOT NULL,
  `id_Usuarios` INT NOT NULL,
  `id_Publicacao` VARCHAR(45) NOT NULL,
  `Comentarios` TEXT NOT NULL,
  `data_comentarios` DATETIME NOT NULL,
  PRIMARY KEY (`idComentarios`, `id_Usuarios`, `id_Publicacao`, `Comentarios`, `data_comentarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Likes` (
  `idLikes` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `data_likes` DATETIME NOT NULL,
  PRIMARY KEY (`idLikes`, `idUsuarios`, `idEmpresa`, `data_likes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacao` (
  `idPublicacao` INT NOT NULL,
  `idEmpres` INT NOT NULL,
  `titulo` TEXT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `imagem` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `data_publicacao` DATETIME NOT NULL,
  PRIMARY KEY (`idPublicacao`, `idEmpres`, `titulo`, `descricao`, `imagem`, `local`, `cidade`, `data_publicacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deslikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deslikes` (
  `idDeslikes` INT NOT NULL,
  `idUsuarios` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `data_deslikes` DATETIME NOT NULL,
  PRIMARY KEY (`idDeslikes`, `idUsuarios`, `idEmpresa`, `data_deslikes`),
  CONSTRAINT `idempresa`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Empresa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `likes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Empresa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `likes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id usuario`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Comentarios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deslikes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Empresa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `deslikes`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Usuarios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usarios`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Empresa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `empresa`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Publicacao` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
